services:
  - type: web
    name: fitzone-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: BOT_TOKEN
        fromService:
          type: secret
          name: bot-token
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
