services:
  - type: web
    name: fitzone-bot
    env: node
    plan: free
    buildCommand: npm ci && npm run build && ls -la dist/ && node debug-paths.js
    startCommand: |
      if [ -f "./dist/index.js" ]; then
        echo "Starting with ./dist/index.js"
        node ./dist/index.js
      elif [ -f "dist/index.js" ]; then
        echo "Starting with dist/index.js"
        node dist/index.js
      else
        echo "ERROR: dist/index.js not found"
        ls -la
        exit 1
      fi
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: BOT_TOKEN
        fromService:
          type: secret
          name: bot-token
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
