services:
  - type: web
    name: fitzone-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fitzone-db
          property: connectionString
      - key: BOT_TOKEN
        fromService:
          type: secret
          name: bot-token
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info

databases:
  - name: fitzone-db
    plan: free
    databaseName: fitzone
    user: fitzone_user
