services:
  - type: web
    name: fitzone-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://lololomik_db_user:Abx8px7c7Rp4Dh0Q@cluster0.bnmqjgg.mongodb.net/fitzone?appName=Cluster0
      - key: BOT_TOKEN
        fromService:
          type: secret
          name: bot-token
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
